server/db/models/user.js

completed user model

---

server/db/models/user.js
server/db/models/user.spec.js

^^^ I added testing and allowNull: false, and validate: notEmpty: true! Coooooool. All tests pass  💯

added testing and validations

---

server/db/models/product.js
server/db/models/product.spec.js

completed product model with tests passing

---

server/db/models/index.js
server/db/models/photo.js
server/db/models/photo.spec.js

Photo model working with an association to productId

---

server/db/models/cart.spec.js

Cart model test

---

server/db/models/category.js
server/db/models/category.spec.js
server/db/models/index.js

category and tests complete

---

server/db/models/address.spec.js

fixed ugly files

---

server/api/index.js
server/api/products.js
server/api/products.spec.js

Product routes

---

server/db/models/index.js

removed carItem associations to fix error

---

package-lock.json
package.json
script/seed/seed-users.js
server/db/models/index.js

users-seed is working - still need to integrate modular seed files.  I had to comment out an association to make this seed file work.

---

script/seed/seed-addresses.js

seed addresses is working

---

script/seed.js
script/seed/seed-addresses.js
script/seed/seed-cart.js
script/seed/seed-images.js
script/seed/seed-products.js
script/seed/seed-review.js
script/seed/seed-users.js

sorta finished

---

package-lock.json
script/seed/seed-categories.js
server/api/users.spec.js

seed categories need to update seed.js

---

script/seed.js
script/seed/seed-cart.js
script/seed/seed-review.js

npm run seed works!

---

package-lock.json
script/seed.js
script/seed/seed-orders.js

Seed orders

---

package-lock.json
server/api/products.js
server/api/products.spec.js
server/api/users.spec.js
server/db/models/address.spec.js
server/db/models/index.js
server/db/models/orderItem.spec.js
server/index.js

IDK y'all i fixed some associatoins and tests

attempted to fix testing:

---

server/db/models/cart.js
server/db/models/cart.spec.js

cart virtual

---

client/app.js
client/components/index.js
client/components/product-item.js
client/components/product-list.js
package-lock.json
package.json
public/caitlin-style.css
public/index.html
public/style.css

🔥 🔥 🔥I set up the individual and all product views with some dummy data. 🔥 🔥 🔥

Product items

---

client/sidebar.js

updated sidebar

---

client/store/index.js
client/store/product.js
client/store/products.js

Did the GET ALL products reducer __ COMPLETE
preemptively set up for admin users to put/post/delete on a product __ INCOMPLETE

Redux products

---

client/components/sidebarleftpush.js
client/store/activecategory.js
client/store/categories.js
client/store/index.js
server/index.js

active category is now on state and categories buttons work!

---

client/components/navbar.js

fixed logout button

---

client/store/index.js

somehow the store product file imports got removed

---

client/components/sidebarleftpush.js

fixed sidebar error

---

client/components/sidebarleftpush.js

Sidebar all

---

server/db/models/order.js

fixed total in db on orders

---

client/components/sidebar.js

error with trying to load a nonexistent image

---

client/components/product-detail.js
client/components/product-view-parts.js
client/components/review-list.js
client/store/index.js
client/store/view-reviews.js

put product  page into components and added reviews redux

---

client/components/product-detail.js
client/components/product-item.js
client/components/review-detail.js
client/components/review-form.js
client/components/review-list.js
client/components/user-home.js
script/seed/seed-review.js

Populate reviews

---

client/app.js
client/components/cart-item.js
client/components/cart.js
client/components/index.js
client/components/product-detail.js
client/components/product-item.js
client/components/product-list.js
client/components/product-view-parts.js
client/components/user-home.js
client/store/cart.js
client/store/index.js
server/api/cart.js

New redux cart

---

client/components/index.js
client/components/products/product-list.js
client/components/products/product-page.js
client/components/products/product-view-parts.js
client/components/products/review-form.js
client/components/products/review-list.js
client/components/search.js
client/routes.js
client/store/product.js
package.json
server/api/products.js

Fixed things

---

client/components/navbar.js
client/components/products/product-item.js
client/components/products/review-form.js
client/components/products/review-list.js
client/routes.js
client/store/view-reviews.js
server/api/products.js

can now post reviews ---- sooooo done

---

client/store/cart.js
server/api/cart.js
server/index.js

Cartbugfix

---

client/components/admin/adminUsersView.js
client/components/admin/adminView.js
client/store/admin.js
server/api/users.js

Admin user

---

script/seed/seed-users.js

hardcoded admin users

---

client/store/categories.js
server/api/admin.js
server/api/categories.js
server/api/users.js
server/utils/gatekeeper.js

It's Monday. 
Admin and User gatekeepers are in place. Woof.

New branch

---

client/components/admin/adminUsersView.js
client/components/admin/adminView.js
client/components/user-home.js
public/caitlin-style.css

User admin ongoing

---

client/components/admin/adminCategoriesView.js
client/components/admin/adminCategoryForm.js
client/components/admin/adminUsersView.js
client/components/admin/adminView.js
client/components/products/product-list.js
client/store/categories.js
public/caitlin-style.css
server/api/categories.js

I can add! 
I can remove! 
The admin view shows how many products are in the category! 
Oh wooowwwww *owen wilson voice*

Admin - Category view post/delete

---

client/components/auth-form.js
client/store/user.js

error message on wrong pw/email + a redirect

---

client/components/admin/adminCategoriesView.js
client/components/admin/adminProductDetail.js
client/components/admin/adminProductForm.js
client/components/admin/adminProductsView.js
client/components/products/product-page.js
client/components/sidebar.js
client/store/categories.js
client/store/product.js
client/store/products.js
public/caitlin-style.css
server/api/products.js
server/utils/helperFunctions.js

Products admin

---

server/api/products.js

fixed my mistake

---

client/components/navbar.spec.js
client/components/user-home.spec.js
client/store/user.spec.js
server/api/admin.spec.js
server/api/categories.spec.js
server/api/products.spec.js
server/api/users.spec.js
server/db/models/address.spec.js
server/db/models/category.spec.js
server/db/models/order.spec.js
server/db/models/orderItem.spec.js
server/db/models/photo.spec.js
server/db/models/product.spec.js
server/db/models/review.spec.js
server/db/models/user.js
server/db/models/user.spec.js

Fixing tests

---

client/components/products/product-list.js
client/components/sidebar.js
script/seed/seed-products.js

Seed db photos

---

client/components/admin/adminProductAddForm.js
client/components/admin/adminProductDetail.js
client/components/admin/adminProductsView.js
client/store/products.js
server/api/products.js

Add product

---

server/api/order.js

mailer was concatenating $ strings, coerced those mfers to numbers
